### PR TITLE
Updated dependency for fix NPM security warning

### LINKED ISSUE #1: NPM Audit reports 1 high severity vulnerability
NPM is reporting security warning because `sieve-of-eratosthenes` was using an insecure version of `minimatch` through an outdated version of `tape`.

### PR DESCRIPTION
**Pull request by mauricedb**
Fixes #1.

Please merge and publish updated package to NPM.

### CODE REVIEW

**Comment by mauricedb** [comment]
@dsernst Any feedback on this? If not please merge and update NPM.

**Comment by dsernst** [comment]
Thx— merged. 

I don't think this should have come up for many people, because the `tape` dependency was only a devDependency of `sieve-of-eratosthenes`, so this package would never get it. But in any case, it's now fixed.

**Comment by dsernst** [comment]
New version pushed to npm 👍

**Comment by mauricedb** [comment]
I was installing `quick-is-prime` and that did result in the rather nasty security warning because of this dependency. Removed my `node_modules` and `package-lock.json` and a new `npm install` found 0 vulnerabilities.

Thanks

**Pull request merged**
